Version bump to chocolatey v2.1.0
crazy-max/ghaction-chocolatey pull request #158
Opened 2023-06-30 15:24 UTC by regg00

Fix #157 

@crazy-max The official Choco repo is currently not building because of a problem with GitVersion so I had to create a patch.
I kept getting this error message in the build logs: `System.InvalidOperationException: Gitversion could not determine which branch to treat as the development branch (default is 'develop') nor release-able branch (default is 'main' or 'master'), either locally or remotely. Ensure the local clone and checkout match the requirements or considering using 'GitVersion Dynamic Repositories'`

I'm pretty sure someone smarter than me can create a better fix, but what I did is working.

2023-06-30 18:27 UTC, regg00 commented
See this commit for more info: https://github.com/chocolatey/choco/commit/2bbe5d711ad1499fef0cb24b70ef4b87ff7fd505

2023-07-01 01:50 UTC, regg00 commented
I opened an issue on the main choco repo https://github.com/chocolatey/choco/issues/3243
Seems that cloning a specific branch causes the issue (ex: `git clone --branch 2.1.0 https://github.com/chocolatey/choco.git`)
If I clone the main repo with `git clone https://github.com/chocolatey/choco.git` it builds without the patch to the GitVersion file.

2023-07-01 13:03 UTC, regg00 commented
Based on this recommendation here https://github.com/chocolatey/choco/issues/3243#issuecomment-1615604532 I modified the Dockerfile to download pre-built binaries from GitHub releases.

I think it's a more robust and simple solution.
@crazy-max Let me know what you think.

2023-07-02 14:16 UTC, crazy-max commented
@regg00 Thanks for working on this!

> Based on this recommendation here [chocolatey/choco#3243 (comment)](https://github.com/chocolatey/choco/issues/3243#issuecomment-1615604532) I modified the Dockerfile to download pre-built binaries from GitHub releases.

Ah they have an official Docker image now, that's handy. Moving forward I think we could just add a `version` input so it would download chocolatey directly from https://github.com/chocolatey/choco/releases so on Windows runners it would install the desired version (if provided) from the MSI or we could just run the official image that seems to support windows too, otherwise it uses the default one installed on the runner. For Linux, if version is provided it takes the tarball from GH release or the image. I think we could just use the official image as version to be fair so by default it would be `latest` and you can put whatever tag you want to use. I will make some changes related to this and keep you posted.

2023-07-02 14:19 UTC, crazy-max commented
Completely forgot we already had the `image` input. Can you try with:

```yaml
      -
        name: Choco help
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          image: chocolatey/choco:v2.1.0
          args: -h
```

2023-07-02 14:26 UTC, crazy-max commented
Oh boy looking at the windows image we can't afford using it looking at its size:

![image](https://github.com/crazy-max/ghaction-chocolatey/assets/1951866/e6615095-3ba3-4677-8afa-f6c2d8e9e57f)

2023-07-02 14:28 UTC, crazy-max commented
Even the linux is quite huge compared to mine: https://hub.docker.com/r/crazymax/ghaction-chocolatey/tags?page=1&ordering=last_updated

![image](https://github.com/crazy-max/ghaction-chocolatey/assets/1951866/0a2c910a-855d-489c-8d5b-523857789ddc)

There should be room for improvements with the official image

2023-07-02 14:30 UTC, crazy-max commented
Will take your PR in the meantime but moving forward I think I will also provide a slim Windows image and create a manifest list for multi-platform support.

2023-07-02 14:35 UTC, crazy-max requested changes

2023-07-02 14:35 UTC, crazy-max commented on image/Dockerfile
> +ARG CHOCOLATEY_VERSION
Should be placed right before `RUN wget` otherwise cache will be evicted for `apk` run.

2023-07-02 14:35 UTC, crazy-max commented on image/Dockerfile
> +RUN apk add --no-cache wget
Would prefer curl:

```suggestion
RUN apk add --no-cache curl
```

2023-07-02 14:35 UTC, crazy-max commented on image/Dockerfile
> +RUN tar -zxvf chocolatey.v${CHOCOLATEY_VERSION}.tar.gz
Oneline cmd:

```suggestion
RUN curl -sSL "https://github.com/chocolatey/choco/releases/download/${CHOCOLATEY_VERSION}/chocolatey.v${CHOCOLATEY_VERSION}.tar.gz" | tar xz
```

2023-07-07 11:41 UTC, regg00 commented
Thanks for the suggestions. 
I edited the code accordingly.

2023-08-31 09:38 UTC, closed without merging